AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - '*.gemspec'
    - 'bin/**'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50

Style/Documentation:
  Enabled: false

